version: '2'

services:
  sylvie-laurent:
    image: sylvie-laurent:0.0.2
    ports:
      - 80:80
    environment:
      - 'Template__Auth__Secret=THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET, IT CAN BE ANY STRING'
      - 'Template__Database__ConnectionString=server=mysql;uid=root;pwd=password;database=app-db'
      - 'Users__AllIn__Username=all-in'
      - 'Users__AllIn__Password=jeleveux'
      - 'Users__Vine__Username=vine'
      - 'Users__Vine__Password=santé'
      - 'Users__NoCeremony__Username=no-ceremony'
      - 'Users__NoCeremony__Password=oui'
      - 'Users__Party__Username=party'
      - 'Users__Party__Password=fiesta'
  mysql:
    image: mysql:8.0.20
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
       - ./data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    ports: 
      - 8080:8080
    restart: always